### ISSUE TITLE
devrel doesn't work

### ISSUE THREAD

**Issue by marksteele** [marianoguerra/rebar3_template_riak_core#7] opened 2016-02-21 04:33 UTC
I'm unable to create a release using this template, it's erroring out with:

```
[root@dev1 bartr]# make release
rebar3 release
===> Verifying dependencies...
===> Compiling bartr
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /root/bartr/_build/default/lib
          /root/bartr/apps
          /usr/lib64/erlang/lib
          /root/bartr/_build/default/rel
===> Resolved bartr-0.1.0
===> Dev mode enabled, release will be symlinked
===> release successfully created!
===> Unable to copy from /root/bartr/_build/default/rel/bartr/releases/0.1.0/vm.args to /root/bartr/_build/default/rel/bartr/etc/vm.args because of {copy_failed,
                                                                                                                                                enoent
```

**Comment by marianoguerra** [comment] 2016-02-21 12:57
I'm trying to find out the reason :)

if you have more info to share please do!

**Comment by marianoguerra** [comment] 2016-02-21 12:57
BTW, I can reproduce it, so repoduction info is not needed, but if you are able to advance share your notes here

**Comment by marianoguerra** [comment] 2016-02-21 13:46
it should be fixed, if you are interested in what was done check this comment https://github.com/tsloughter/rebar3_cuttlefish/issues/3#issuecomment-186824932

you will have to pull the latest changes from the template or refetch it and create the project again, if you have a project with changes already, create a new project with the same name somewhere else and check the differences in rebar.config and Makefile

**Comment by marksteele** [comment] 2016-02-22 02:31
Fixed the first issue however now:

```
21:02:34.800 [info] New capability: {riak_core,net_ticktime} = true

=CRASH REPORT==== 21-Feb-2016::21:02:34 ===
  crasher:
    initial call: application_master:init/4
    pid: <0.620.0>
    registered_name: []
    exception exit: {bad_return,
                     {{riak_core_app,start,[normal,[]]},
                      {'EXIT',
                       {{badmatch,
                         {error,
                          {invalid_config_keys,
                           ["transfer_limit ","handoff.outbound ",
                            "handoff.inbound "]}}},
                        [{riak_core_handoff_cli,register_config_whitelist,0,
                          [{file,
                            "/root/bartr/_build/default/lib/riak_core/src/riak_core_handoff_cli.erl"},
                           {line,63}]},
                         {riak_core_handoff_cli,register_cli,0,
                          [{file,
                            "/root/bartr/_build/default/lib/riak_core/src/riak_core_handoff_cli.erl"},
                           {line,32}]},
                         {clique,'-register/1-lc$^0/1-0-',1,
                          [{file,
                            "/root/bartr/_build/default/lib/clique/src/clique.erl"},
                           {line,42}]},
                         {clique,register,1,
                          [{file,
                            "/root/bartr/_build/default/lib/clique/src/clique.erl"},
                           {line,42}]},
                         {riak_core_app,start,2,
                          [{file,
                            "/root/bartr/_build/default/lib/riak_core/src/riak_core_app.erl"},
                           {line,106}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,272}]}]}}}}
      in function  application_master:init/4 (application_master.erl, line 133)
    ancestors: [<0.619.0>]
    messages: [{'EXIT',<0.621.0>,normal}]
    links: [<0.619.0>,<0.505.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 209
  neighbours:
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,riak_core,{bad_return,{{riak_core_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{invalid_config_keys,[\"transfer_limit \",\"handoff.outbound \",\"handoff.inbound \"]}}},[{riak_core_handoff_cli,register_config_whitelist,0,[{file,\"/root/bartr/_build/default/lib/riak_core/src/riak_core_handoff_cli.erl\"},{line,63}]},{riak_core_handoff_cli,register_cli,0,[{file,\"/root/bartr/_build/default/lib/riak_core/src/riak_core_handoff_cli.erl\"},{line,32}]},{clique,'-register/1-lc$^0/1-0-',1,[{file,\"/root/bartr/_build/default/lib/clique/src/clique.erl\"},{line,42}]},{clique,register,1,[{file,\"/root/bartr/_build/default/lib/clique/src/clique.erl\"},{line,42}]},{riak_core_app,start,2,[{file,\"/root/bartr/_build/default/lib/riak_core/src/riak_core_app.erl\"},{line,106}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,272}]}]}}}}}"}

Crash dump was written to: erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,riak_core,{bad_return,{{riak_core_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{invalid_config_keys,["transfer_limit ",
```

This is off a clean 

```
rebar3 new rebar3_riak_core name=bartr
cd bartr/
rebar3 release
rebar3 run
```

**Comment by marksteele** [comment] 2016-02-22 02:36
Also:

```
[root@dev3 bartr]# make
rebar3 cuttlefish release
===> Command cuttlefish not found
make: *** [release] Error 1

```

**Comment by marianoguerra** [comment] 2016-02-24 07:15
@marksteele try now from scratch with the latest rebar3, it should work.

let me know if you have any problem.

**Closed as completed** 2018-01-22 09:50 UTC
